fix: update Dockerfile to use node:22.19.0 and correct package paths for bot

diff --git a/packages/bot/Dockerfile b/packages/bot/Dockerfile
--- a/packages/bot/Dockerfile
+++ b/packages/bot/Dockerfile
@@ -1,40 +1,47 @@
-FROM ghcr.io/alwatr/node:22.15.1 AS builder
+FROM ghcr.io/alwatr/node:22.19.0 AS builder
 
 RUN set -ex; \
   apk add --no-cache git; \
   corepack enable;
 
 COPY package.json yarn.lock ./
-COPY packages/api/package.json packages/api/
+COPY packages/bot/package.json packages/bot/
 
 RUN yarn install;
 
 COPY . .
 
+ENV NODE_ENV development
+
 RUN set -eux; \
   yarn install --immutable; \
   yarn build; \
   ls -lahF .; \
-  ls -RlahF /app/packages/api;
+  ls -RlahF /app/packages/bot;
 
 # ---
 
-FROM ghcr.io/alwatr/node:22.15.1
-LABEL org.opencontainers.image.base.name="ghcr.io/alwatr/node:22.15.1"
+FROM ghcr.io/alwatr/node:22.19.0
+LABEL org.opencontainers.image.base.name="ghcr.io/alwatr/node:22.19.0"
 
-RUN apk add --no-cache curl
-HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --start-interval=1s --retries=3 CMD curl -fso /dev/null http://localhost/health || exit 1
+# RUN apk add --no-cache curl
+# HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --start-interval=1s --retries=3 CMD curl -fso /dev/null http://localhost/health || exit 1
 
-COPY --from=builder /app/packages/api/dist/ .
-# RUN set -ex; \
-#   corepack enable; \
-#   npm install sharp;
-# RUN set -eux; ls -RlahF /app;
+COPY --from=builder /app/packages/bot/start.sh .
+RUN chmod +x ./start.sh
+CMD ["./start.sh"]
 
-# ENV NODE_OPTIONS --enable-source-maps
 ENV host="0.0.0.0" \
     port="80"
-
 EXPOSE 80
 
-CMD ["node", "main.mjs"]
+# TODO: move untill this line to alwatr/nanotron
+
+RUN set -ex; \
+  corepack enable; \
+  npm install grammy;
+
+ENV NODE_OPTIONS --enable-source-maps
+
+COPY --from=builder /app/packages/bot/dist/ .
+# RUN set -eux; ls -RlahF /app;
